name: Update README

on:
  schedule:
    - cron: "0 0 * * *" # Ежедневное обновление
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Update README Stats
      run: |
        USERNAME=$(git config user.name)
        sed -i "s/username=.*&layout/username=$goringich&layout/" README.md

    - name: Commit Changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add README.md
        git commit -m "Update GitHub Stats in README"
        git push
